<?php

namespace Ecommerce\EcommerceBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CommentaireController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Ecommerce\EcommerceBundle\Controller\CommentaireController();
        return $instance;
    }
}
