<?php

namespace Pages\PagesBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PagesAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Pages\PagesBundle\Controller\PagesAdminController();
        return $instance;
    }
}
