<?php

namespace Utilisateurs\UtilisateursBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UtilisateursController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Utilisateurs\UtilisateursBundle\Controller\UtilisateursController();
        return $instance;
    }
}
